#!/usr/bin/env bash
#cito M:644 O:0 G:0 T:/usr/share/bash-completion/completions/redshifter
#------------------------------------------------------------------------------
# Project Name      - PerlProjects/source/redshifter/completions
# Started On        - Tue 12 Jan 22:56:08 GMT 2021
# Last Change       - Sat 22 Jan 00:09:49 GMT 2022
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# This is the bash completion script for Redshifter.
#------------------------------------------------------------------------------

_redshifter() {
	local Option Arg Args

	while read; do
		if [[ $REPLY =~ ^[[:space:]]{2} ]]; then
			Option=${REPLY%% - *}
			for Arg in ${Option//,/}; {
				Args+="${Arg##[^-]*} "
			}
		fi
	done <<< "$(redshifter -h)"

	if [[ $2 == -* ]]; then
		COMPREPLY=(`compgen -W "$Args" -- "$2"`)
	else
		# Too much of a pain to parse the Usage() output for these. If a new
		# action is added, this must be updated for completion to work for it.
		COMPREPLY=(`compgen -W 'lower raise reset set show' -- "$2"`)
	fi
}

complete -F _redshifter redshifter
