#!/usr/bin/env bash
#cito M:644 O:0 G:0 T:/usr/share/bash-completion/completions/i3-active
#------------------------------------------------------------------------------
# Project Name      - PerlProjects/source/i3-active/completions
# Started On        - Mon 29 Jan 18:47:58 GMT 2018
# Last Change       - Sat 22 Jan 00:10:08 GMT 2022
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# This is the bash completion script for i3 Active.
#
#TODO: Add completion support for the valid keys.
#------------------------------------------------------------------------------

_i3_active() {
	local Option Arg Args Packages

	while read; do
		if [[ $REPLY =~ ^[[:space:]]{2} ]]; then
			Option=${REPLY%% - *}
			for Arg in ${Option//,/}; {
				Args+="${Arg##[^-]*} "
			}
		fi
	done <<< "$(i3-active -h)"

	COMPREPLY=($(compgen -W "$Args" -- "$2"))
}

complete -F _i3_active i3-active
