#!/usr/bin/env bash
#cito M:644 O:0 G:0 T:/usr/share/bash-completion/completions/apt-history
#------------------------------------------------------------------------------
# Project Name      - PerlProjects/source/apt-history/completions
# Started On        - Mon 29 Jan 18:47:58 GMT 2018
# Last Change       - Mon 11 Jan 16:39:30 GMT 2021
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# This is the bash completion script for apt-history.
#------------------------------------------------------------------------------

_apthistory(){
	GetArgs(){
		local CurLine Word

		while read -a Line; do
			[ "${Line[0]:0:1}" == '-' ] || continue

			for Field in "${Line[@]}"; {
				if [ "$Field" == '-' ]; then
					break
				elif [[ $Field == -* ]]; then
					Field=${Field//\[*\]/}
					printf '%s ' "${Field//,/}"
				fi
			}
		done <<< "$(apt-history -h)"
	}

	if [ $3 == '-p' ] || [ $3 == '--package' ]; then
		local Packages=`_xfunc dpkg _comp_dpkg_installed_packages`
		COMPREPLY=(`compgen -W "$Packages" -- "$2"`)
	elif [ $3 == '-A' ] || [ $3 == '--action' ]; then
		COMPREPLY=(`compgen -W 'Install Purge Remove Upgrade' -- "$2"`)
	elif [ $3 == '-D' ] || [ $3 == '--display' ]; then
		COMPREPLY=(`compgen -W 'OneLine Wrapped' -- "$2"`)
	else
		COMPREPLY=(`compgen -W "$(GetArgs)" -- "$2"`)
	fi
}

complete -F _apthistory apt-history
