#!/usr/bin/env bash
#cito M:644 O:0 G:0 T:/usr/share/bash-completion/completions/apt-history
#------------------------------------------------------------------------------
# Project Name      - PerlProjects/source/apt-history/completions
# Started On        - Mon 29 Jan 18:47:58 GMT 2018
# Last Change       - Thu 26 Nov 05:55:47 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# This is the bash completion script for apt-history.
#------------------------------------------------------------------------------

_apthistory(){
	GetArgs(){
		local CurLine Word

		while read -a Line; do
			[ "${Line[0]:0:1}" == '-' ] || continue

			for Field in "${Line[@]}"; {
				if [ "$Field" == '-' ]; then
					break
				elif [[ $Field == -* ]]; then
					Field=${Field//\[*\]/}
					printf '%s ' "${Field//,/}"
				fi
			}
		done <<< "$(apt-history -h)"
	}

	COMPREPLY=($(compgen -W "$(GetArgs)" -- "$2"))
}

complete -F _apthistory -o default apt-history
