#!/usr/bin/env bash
#cito M:644 O:0 G:0 T:/usr/share/bash-completion/completions/apt-history
#------------------------------------------------------------------------------
# Project Name      - PerlProjects/source/apt-history/completions
# Started On        - Mon 29 Jan 18:47:58 GMT 2018
# Last Change       - Sat 22 Jan 00:10:56 GMT 2022
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# This is the bash completion script for APT History.
#------------------------------------------------------------------------------

_apthistory() {
	local Option Arg Args Packages

	while read; do
		if [[ $REPLY =~ ^[[:space:]]{2} ]]; then
			Option=${REPLY%% - *}
			for Arg in ${Option//,/}; {
				Args+="${Arg##[^-]*} "
			}
		fi
	done <<< "$(apt-history -h)"

	if [[ $3 == -p || $3 == --package ]]; then
		Packages=`_xfunc dpkg _comp_dpkg_installed_packages`
		COMPREPLY=(`compgen -W "$Packages" -- "$2"`)
	elif [[ $3 == -A || $3 == --action ]]; then
		COMPREPLY=(`compgen -W 'Install Purge Remove Upgrade' -- "$2"`)
	elif [[ $3 == -D || $3 == --display ]]; then
		COMPREPLY=(`compgen -W 'OneLine Wrapped' -- "$2"`)
	else
		COMPREPLY=(`compgen -W "$Args" -- "$2"`)
	fi
}

complete -F _apthistory apt-history
