#!/usr/bin/env bash
#cito M:644 O:0 G:0 T:/usr/share/bash-completion/completions/i3-workspaces
#------------------------------------------------------------------------------
# Project Name      - PerlProjects/source/i3-workspaces/completions
# Started On        - Mon 29 Jan 18:47:58 GMT 2018
# Last Change       - Fri 21 Jan 18:18:58 GMT 2022
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# This is the bash completion script for i3 Workspaces.
#
#TODO: Add completion support for the valid keys.
#------------------------------------------------------------------------------

_i3_workspaces() {
	GetArgs() {
		local CurLine Word Field Line

		while read -a Line; do
			[[ ${Line[0]:0:1} == - ]] || continue

			for Field in "${Line[@]}"; {
				if [ "$Field" == '-' ]; then
					break
				elif [[ $Field == -* ]]; then
					Field=${Field//\[*\]/}
					printf '%s ' "${Field//,/}"
				fi
			}
		done <<< "$(i3-workspaces -h)"
	}

	COMPREPLY=($(compgen -W "$(GetArgs)" -- "$2"))

	unset -f GetArgs
}

complete -F _i3_workspaces i3-workspaces
