#!/usr/bin/env bash
#cito M:644 O:0 G:0 T:/usr/share/bash-completion/completions/gitsap
#----------------------------------------------------------------------------------
# Project Name      - PerlProjects/source/completions/gitsap
# Started On        - Sun 19 Jan 17:45:28 GMT 2020
# Last Change       - Fri 24 Jan 18:53:27 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# This is the bash completion script for gitsap.
#----------------------------------------------------------------------------------#----------------------------------------------------------------------------------

_gitsap(){
	GetArgs(){
		local IsOpts F1 F2 _
		gitsap -h | while read F1 F2 _; do
			if [ "$F1" = 'OPTS:' ]; then
				printf '%s ' "${F2//|/ }"
				IsOpts='true'
			elif [ "$IsOpts" = 'true' ]; then
				case $F1 in
					-*)
						printf '%s ' "${F1//|/ }"
						[ -z "$F1" ] && break ;;
					*) continue ;;
				esac
			fi
		done
	}

	COMPREPLY=(`compgen -W "$(GetArgs)" -- "$2"`)
}

complete -F _gitsap gitsap
