#!/usr/bin/env bash
#cito M:644 O:0 G:0 T:/usr/share/bash-completion/completions/previewer
#------------------------------------------------------------------------------
# Project Name      - PerlProjects/source/previewer/completions
# Started On        - Mon 29 Jan 18:47:58 GMT 2018
# Last Change       - Sat 22 Jan 00:11:13 GMT 2022
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# This is the bash completion script for previewer.
#------------------------------------------------------------------------------

_previewer() {
	local Option Arg Args

	while read; do
		if [[ $REPLY =~ ^[[:space:]]{2} ]]; then
			Option=${REPLY%% - *}
			for Arg in ${Option//,/}; {
				Args+="${Arg##[^-]*} "
			}
		fi
	done <<< "$(previewer -h)"

	COMPREPLY=($(compgen -W "$Args" -- "$2"))
}

complete -F _previewer -o default previewer
