#!/usr/bin/env bash
#cito M:644 O:0 G:0 T:/usr/share/bash-completion/completions/dominator
#------------------------------------------------------------------------------
# Project Name      - PerlProjects/source/dominator/completions
# Started On        - Thu 19 Mar 02:22:35 GMT 2020
# Last Change       - Thu 19 Mar 02:22:49 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# This is the bash completion script for `dominator`.
#------------------------------------------------------------------------------

_dominator(){
	while read; do
		if [[ $REPLY =~ ^[[:space:]]{2} ]]; then
			Option=${REPLY%% - *}
			for Arg in ${Option//,/}; {
				Args+="${Arg##[^-]*} "
			}
		fi
	done <<< "$(dominator -h)"

	COMPREPLY=(`compgen -W "$Args" -- "$2"`)

	unset Option Arg Args
}

complete -F _dominator dominator
