#!/usr/bin/env perl
#cito M:755 O:0 G:0 T:/usr/bin/dominator
#------------------------------------------------------------------------------
# Project Name      - PerlProjects/source/dominator/dominator
# Started On        - Thu 19 Mar 01:01:47 GMT 2020
# Last Change       - Thu 19 Mar 01:10:00 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# A Perl interpretation and revision of an interesting `domains.sh` program
# (AKA: DomainEnum), written in Shell (Bash), by GitHub user `bing0o`.
#
#   https://github.com/bing0o/bash_scripting
#
# Features:
#
# N/A
#
# Bugs:
#
# N/A
#
# Dependencies:
#
#   libtfl-perl (>= 2020-01-03)
#   libwww-perl (>= 6.15-1)
#   perl (>= 5.22.1-9)
#------------------------------------------------------------------------------

use strict;
use warnings;
use autodie;
use LWP::UserAgent;
use TFL 'Err';

no warnings 'uninitialized';

my $CurVer = '2020-03-19';

sub Usage{
	print(qq{Usage: $TFL::PROGNAME [OPTS]

		  -h, --help               - Display this help information.
		  -v, --version            - Output the version datestamp.
	} =~ tr/\t//dr)
}

while (defined($ARGV[0])){
	if ($ARGV[0] =~ '^(--help|-h)$'){
		Usage(); exit(0)
	}elsif ($ARGV[0] =~ '^(--version|-v)$'){
		print("$CurVer\n"); exit(0)
	}elsif ($ARGV[0] =~ '^-'){
		Err(1, "Incorrect option(s) specified.")
	}else{
		last
	}

	shift()
}


