#!/usr/bin/perl

#------------------------------------------------------------------------------
# Project Name      - PerlProjects/source/local-im-client/local-im-client
# Started On        - Mon 26 Oct 15:03:04 GMT 2020
# Last Change       - Mon 26 Oct 17:22:53 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# Features:
#
# N/A
#
# Bugs:
#
# N/A
#
# Dependencies:
#
#   libglib-perl (>= 3:1.326-1build1)
#   libgtk2-perl (>= 2:1.24992-1build1)
#   perl (>= 5.22.1-9)
#------------------------------------------------------------------------------

use strict;
use warnings;
use autodie;
use Gtk2 '-init';
use Glib 'TRUE', 'FALSE';

no warnings 'uninitialized';

my $Progrm = 'Local IM Client';

#-------------------------------------------------------------------Subroutines

# Placeholder for info dialogs; still using Gtk2::Window for flexibility.
sub InfoWin{
}

# Placeholder for error dialogs; still using Gtk2::Window for flexibility.
sub ErrWin{
}

# Placeholder for the settings window.
sub Settings{
}

sub MenuInit{
	my $MenuBar = Gtk2::MenuBar->new();
		$MenuBar->set_border_width(4);

	# The Tools Item for the MenuBar.
	my $MenuItemTools = Gtk2::MenuItem->new('_Tools');

	# The Tools submenu.
	my $MenuTools = Gtk2::Menu->new();

	# MenuItems for the Tools Menu.
	my $MenuItemRefresh = Gtk2::MenuItem->new('_Refresh');
		$MenuItemRefresh->signal_connect(
			'activate' => sub {
				print("MenuItemRefresh clicked.\n")
			}
		);

	my $MenuItemArchive = Gtk2::MenuItem->new('_Archive Chat');
		$MenuItemArchive->signal_connect(
			'activate' => sub {
				print("MenuItemArchive clicked.\n")
			}
		);

	my $MenuItemSettings = Gtk2::MenuItem->new('_Settings...');
		$MenuItemSettings->signal_connect(
			'activate' => sub {
				print("MenuItemSettings clicked.\n")
			}
		);

	# Add MenuItems (whether submenus or not) to MenuBar.
	$MenuBar->append($MenuItemTools);

	# Set MenuItemTools to use MenuTools as a submenu.
	$MenuItemTools->set_submenu($MenuTools);

	# Add MenuItems to the Tools submenu.
	$MenuTools->append($MenuItemRefresh);
	$MenuTools->append(Gtk2::SeparatorMenuItem->new());
	$MenuTools->append($MenuItemArchive);
	$MenuTools->append(Gtk2::SeparatorMenuItem->new());
	$MenuTools->append($MenuItemSettings);

	# This is then used when later packing the VBox.
	return($MenuBar)
}

#------------------------------------------------------------Initialize Widgets

my $RootWin = Gtk2::Window->new();
	$RootWin->signal_connect('destroy' => sub {Gtk2::main_quit()});
	$RootWin->signal_connect('delete_event' => sub {return(0)});

	$RootWin->set_position('center_always');
	$RootWin->set_default_size(680, 640);
	$RootWin->set_title($Progrm);
	$RootWin->set_border_width(4);
	$RootWin->set_resizable(TRUE);
	$RootWin->set_decorated(TRUE);

my $VBoxMain = Gtk2::VBox->new(FALSE, 4);
	$VBoxMain->set_border_width(8);

my $HBoxChat = Gtk2::HBox->new(FALSE, 4);
	$HBoxChat->set_border_width(8);

my $SWData = Gtk2::ScrolledWindow->new(undef, undef);
	$SWData->set_shadow_type('etched-out');
	$SWData->set_policy('automatic', 'automatic');
	$SWData->set_size_request(0, 600);
	$SWData->set_border_width(12);

my $FrameData = Gtk2::Frame->new('Local Chat');
	$FrameData->set_border_width(2);

my $FrameEnterMSG = Gtk2::Frame->new('Enter Message');

my $FrameEntry = Gtk2::Frame->new('Local Messages');
	$FrameEntry->set_border_width(2);

my $DataBuffer = Gtk2::TextBuffer->new();

my $SendButton = Gtk2::Button->new('    Send    ');

my $DataView = Gtk2::TextView->new_with_buffer($DataBuffer);
	$DataView->set_cursor_visible(FALSE);
	$DataView->set_editable(FALSE);

my $EnterMSG = Gtk2::Entry->new();
	$EnterMSG->signal_connect('activate' => sub {});

#------------------------------------------------Add, Pack, Show, and Main Loop

$RootWin->add($VBoxMain);

$VBoxMain->pack_start(MenuInit(), FALSE, FALSE, 0);
$VBoxMain->pack_start($FrameData, TRUE, TRUE, 4);
$VBoxMain->pack_end($FrameEnterMSG, TRUE, TRUE, 4);

$FrameEnterMSG->add($HBoxChat);

$HBoxChat->pack_start($EnterMSG, TRUE, TRUE, 4);
$HBoxChat->pack_end($SendButton, FALSE, FALSE, 4);

$SWData->add($DataView);
$FrameData->add($SWData);

$RootWin->show_all();

Gtk2::main($Progrm)
