#!/usr/bin/env bash
#cito M:644 O:0 G:0 T:/usr/share/bash-completion/completions/apt-undo-install
#------------------------------------------------------------------------------
# Project Name      - PerlProjects/source/apt-undo-install/completions
# Started On        - Mon 29 Jan 18:47:58 GMT 2018
# Last Change       - Tue 12 Jan 00:31:54 GMT 2021
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# This is the bash completion script for apt-undo-install.
#------------------------------------------------------------------------------

_aptundoinstall(){
	GetArgs(){
		local Line Field

		while read -a Line; do
			[ "${Line[0]:0:1}" == '-' ] || continue

			for Field in "${Line[@]}"; {
				if [ "$Field" == '-' ]; then
					break
				elif [[ $Field == -* ]]; then
					Field=${Field//\[*\]/}
					printf '%s ' "${Field//,/}"
				fi
			}
		done <<< "$(apt-undo-install -h)"
	}

	if [ "$3" == '-l' ] || [ "$3" == '--logfile' ]; then
		COMPREPLY=(`compgen -o default -- "$2"`)
	else
		COMPREPLY=(`compgen -W "$(GetArgs)" -- "$2"`)
	fi
}

complete -F _aptundoinstall apt-undo-install
