#!/usr/bin/env bash
#cito M:644 O:0 G:0 T:/usr/share/bash-completion/completions/lspkg
#------------------------------------------------------------------------------
# Project Name      - PerlProjects/source/lspkg/completions
# Started On        - Fri  8 Apr 00:20:32 BST 2022
# Last Change       - Fri  8 Apr 00:21:17 BST 2022
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# This is the bash completion script for lspkg.
#------------------------------------------------------------------------------

_lspkg() {
	local Option Arg Args Packages

	_pkgs() {
		if . /usr/share/bash-completion/completions/dpkg; then
			_xfunc /usr/bin/dpkg _comp_dpkg_installed_packages "$1"
		fi
	}

	while read; do
		if [[ $REPLY =~ ^[[:space:]]{2} ]]; then
			Option=${REPLY%% - *}
			for Arg in ${Option//,/}; {
				Args+="${Arg##[^-]*} "
			}
		fi
	done <<< "$(lspkg -h)"

	if [[ $3 == -p || $3 == --priority ]]; then
		Priorities='extra important optional required'
		COMPREPLY=(`compgen -W "$Priorities" -- "$2"`)
	elif [[ $2 == -* ]]; then
		COMPREPLY=(`compgen -W "$Args" -- "$2"`)
	else
		COMPREPLY=(`compgen -W "$(_pkgs "$2")" -- "$2"`)
	fi
}

complete -F _lspkg lspkg
