#!/usr/bin/perl

#------------------------------------------------------------------------------
# Project Name      - PerlProjects/source/local-im-client/lam
# Started On        - Mon 26 Oct 15:03:04 GMT 2020
# Last Change       - Mon 26 Oct 23:04:05 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# [L]eave [a] [M]essage. Intended for a local machine. This is a work in
# progress; as such, it's not yet worth using.
#
# Features:
#
# N/A
#
# Bugs:
#
# N/A
#
# Dependencies:
#
#   libglib-perl (>= 3:1.326-1build1)
#   libgtk2-perl (>= 2:1.24992-1build1)
#   perl (>= 5.22.1-9)
#------------------------------------------------------------------------------

use strict;
use warnings;
use autodie;
use Gtk2 '-init';
use Glib 'TRUE', 'FALSE';

no warnings 'uninitialized';

my $Progrm = 'LAM';

#---------------------------------------------------------Process LIMC Settings


#-------------------------------------------------------------------Subroutines

# Informational dialog with OK button. Leaves RootWin in-tact.
sub InfoWin{
	my $Message = shift();

	my $InfoWin = Gtk2::Window->new();
		$InfoWin->signal_connect('destroy' => sub {$_[0]->destroy()});

		$InfoWin->set_position('center_always');
		$InfoWin->set_title($Progrm . ' (Info)');
		$InfoWin->set_border_width(4);
		$InfoWin->set_default_size(280, 100);
		$InfoWin->set_resizable(TRUE);
		$InfoWin->set_decorated(TRUE);
		$InfoWin->activate_focus();

	my $InfoVBox = Gtk2::VBox->new(FALSE, 4);
		$InfoVBox->set_border_width(8);

	my $InfoHBox = Gtk2::HBox->new(FALSE, 4);

	my $MSGLabel = Gtk2::Label->new($Message);
		$MSGLabel->set_single_line_mode(FALSE);
		$MSGLabel->set_line_wrap(TRUE);
		$MSGLabel->set_line_wrap_mode('word');
		$MSGLabel->set_justify('fill');

	my $MSGOKButton = Gtk2::Button->new_with_mnemonic('      _OK      ');
		$MSGOKButton->signal_connect('clicked' => sub {$InfoWin->destroy()});

	$InfoWin->add($InfoVBox);

	$InfoVBox->pack_start($MSGLabel, TRUE, FALSE, 4);
	$InfoVBox->pack_start($InfoHBox, TRUE, TRUE, 4);

	# Having the OK button in its own HBox ensures it's centered.
	$InfoHBox->pack_start($MSGOKButton, TRUE, FALSE, 4);

	$InfoWin->show_all()
}

# Placeholder for error dialogs; still using Gtk2::Window for flexibility.
sub ErrWin{
}

sub Settings{
	my $SetWin = Gtk2::Window->new();
		$SetWin->set_title("$Progrm (Settings)");
		$SetWin->set_position('center_always');
		$SetWin->set_border_width(8);
		$SetWin->set_default_size(500, 140);
		$SetWin->set_resizable(TRUE);
		$SetWin->set_decorated(TRUE);

	my $VBoxSet = Gtk2::VBox->new(FALSE, 4);

	my $HBoxSetTop = Gtk2::HBox->new(FALSE, 4);
		$HBoxSetTop->set_border_width(4);

	my $HBoxSetMiddle = Gtk2::HBox->new(FALSE, 4);
		$HBoxSetMiddle->set_border_width(4);

	my $HBoxSetBottom = Gtk2::HBox->new(FALSE, 4);
		$HBoxSetBottom->set_border_width(4);

	my $HBoxSetMainButtons = Gtk2::HBox->new(FALSE, 4);

	# Applies the settings window but leaves it open.
	my $ApplyButton = Gtk2::Button->new_with_mnemonic('_Apply');
		$ApplyButton->signal_connect('clicked' => sub {});

	# Applies the changes made and also destroys the settings window.
	my $SaveCloseButton = Gtk2::Button->new_with_mnemonic('_Save & Close');
		$SaveCloseButton->signal_connect('clicked' => sub {});

	# Closes the settings window without applying any of the changes.
	my $CancelButton = Gtk2::Button->new_with_mnemonic('_Cancel');
		$CancelButton->signal_connect('clicked' => sub {$SetWin->destroy()});

	my $MSGFileFrame = Gtk2::Frame->new('Chat File Location');
		$MSGFileFrame->set_border_width(8);

	my $MSGFileEntry = Gtk2::Entry->new();

	my $MSGFileHBox = Gtk2::HBox->new(FALSE, 4);
		$MSGFileHBox->set_border_width(8);

	$MSGFileHBox->pack_start($MSGFileEntry, TRUE, TRUE, 4);

	$MSGFileFrame->add($MSGFileHBox);
		$MSGFileFrame->set_border_width(8);

	# Just the one Box for this frame, to keep the sizing consistent.
	$HBoxSetTop->pack_start($MSGFileFrame, TRUE, TRUE, 4);

	$VBoxSet->pack_start($HBoxSetTop, TRUE, TRUE, 4);
	$VBoxSet->pack_start($HBoxSetMiddle, TRUE, TRUE, 4);
	$VBoxSet->pack_start($HBoxSetBottom, TRUE, TRUE, 4);
	$VBoxSet->pack_start($HBoxSetMainButtons, TRUE, TRUE, 4);

	$HBoxSetMainButtons->pack_start($ApplyButton, TRUE, TRUE, 4);
	$HBoxSetMainButtons->pack_start($SaveCloseButton, TRUE, TRUE, 4);
	$HBoxSetMainButtons->pack_start($CancelButton, TRUE, TRUE, 4);

	$SetWin->add($VBoxSet);

	$SetWin->show_all()
}

sub MenuInit{
	my $MenuBar = Gtk2::MenuBar->new();
		$MenuBar->set_border_width(4);

	# The Tools Item for the MenuBar.
	my $MenuItemTools = Gtk2::MenuItem->new('_Tools');

	# The Tools submenu.
	my $MenuTools = Gtk2::Menu->new();

	# MenuItems for the Tools Menu.
	my $MenuItemRefresh = Gtk2::MenuItem->new('_Refresh');
		$MenuItemRefresh->signal_connect(
			'activate' => sub {print("MenuItemRefresh clicked.\n")}
		);

	my $MenuItemArchive = Gtk2::MenuItem->new('_Archive Chat');
		$MenuItemArchive->signal_connect(
			'activate' => sub {print("MenuItemArchive clicked.\n")}
		);

	my $MenuItemSettings = Gtk2::MenuItem->new('_Settings...');
		$MenuItemSettings->signal_connect('activate' => \&Settings);

	# Add MenuItems (whether submenus or not) to MenuBar.
	$MenuBar->append($MenuItemTools);

	# Set MenuItemTools to use MenuTools as a submenu.
	$MenuItemTools->set_submenu($MenuTools);

	# Add MenuItems to the Tools submenu.
	$MenuTools->append($MenuItemRefresh);
	$MenuTools->append(Gtk2::SeparatorMenuItem->new());
	$MenuTools->append($MenuItemArchive);
	$MenuTools->append(Gtk2::SeparatorMenuItem->new());
	$MenuTools->append($MenuItemSettings);

	# This is then used when later packing the VBox.
	return($MenuBar)
}

#------------------------------------------------------------Initialize Widgets

my $RootWin = Gtk2::Window->new();
	$RootWin->signal_connect('destroy' => sub {Gtk2::main_quit()});
	$RootWin->signal_connect('delete_event' => sub {return(0)});

	$RootWin->set_position('center_always');
	$RootWin->set_default_size(680, 640);
	$RootWin->set_title($Progrm);
	$RootWin->set_border_width(4);
	$RootWin->set_resizable(TRUE);
	$RootWin->set_decorated(TRUE);

my $VBoxMain = Gtk2::VBox->new(FALSE, 4);
	$VBoxMain->set_border_width(8);

my $HBoxChat = Gtk2::HBox->new(FALSE, 4);
	$HBoxChat->set_border_width(8);

my $SWData = Gtk2::ScrolledWindow->new(undef, undef);
	$SWData->set_shadow_type('etched-out');
	$SWData->set_policy('automatic', 'automatic');
	$SWData->set_size_request(0, 600);
	$SWData->set_border_width(12);

my $FrameData = Gtk2::Frame->new('Local Chat');
	$FrameData->set_border_width(2);

my $FrameEnterMSG = Gtk2::Frame->new('Enter Message');

my $FrameEntry = Gtk2::Frame->new('Local Messages');
	$FrameEntry->set_border_width(2);

my $DataBuffer = Gtk2::TextBuffer->new();

my $SendButton = Gtk2::Button->new('    Send    ');

my $DataView = Gtk2::TextView->new_with_buffer($DataBuffer);
	$DataView->set_cursor_visible(FALSE);
	$DataView->set_editable(FALSE);

my $EnterMSG = Gtk2::Entry->new();
	$EnterMSG->signal_connect('activate' => sub {});

#------------------------------------------------Add, Pack, Show, and Main Loop

$RootWin->add($VBoxMain);

$VBoxMain->pack_start(MenuInit(), FALSE, FALSE, 0);
$VBoxMain->pack_start($FrameData, TRUE, TRUE, 4);
$VBoxMain->pack_end($FrameEnterMSG, TRUE, TRUE, 4);

$FrameEnterMSG->add($HBoxChat);

$HBoxChat->pack_start($EnterMSG, TRUE, TRUE, 4);
$HBoxChat->pack_end($SendButton, FALSE, FALSE, 4);

$SWData->add($DataView);
$FrameData->add($SWData);

$RootWin->show_all();

Settings();

Gtk2::main($Progrm)
