#!/usr/bin/env bash
#cito M:644 O:0 G:0 T:/usr/share/bash-completion/completions/cheater
#------------------------------------------------------------------------------
# Project Name      - PerlProjects/source/cheater/completions
# Started On        - Mon 29 Jan 18:47:58 GMT 2018
# Last Change       - Tue 24 Nov 02:58:25 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# This is the bash completion script for `cheater`.
#------------------------------------------------------------------------------

_cheater(){
	while read; do
		if [[ $REPLY =~ ^[[:space:]]{2} ]]; then
			Option=${REPLY%% - *}
			for Arg in ${Option//,/}; {
				Args+="${Arg##[^-]*} "
			}
		fi
	done <<< "$(cheater -h)"

	COMPREPLY=(`compgen -W "$Args" -- "$2"`)

	unset Option Arg Args
}

complete -F _cheater cheater
