#!/usr/bin/env bash
#cito M:644 O:0 G:0 T:/usr/share/bash-completion/completions/dtp
#------------------------------------------------------------------------------
# Project Name      - PerlProjects/source/dtp/completions
# Started On        - Sat  6 Mar 03:21:01 GMT 2021
# Last Change       - Sat 22 Jan 00:10:38 GMT 2022
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# This is the BASH completion script for `dtp`.
#------------------------------------------------------------------------------

_dtp() {
	local Option Arg Args Packages

	while read; do
		if [[ $REPLY =~ ^[[:space:]]{2} ]]; then
			Option=${REPLY%% - *}
			for Arg in ${Option//,/}; {
				Args+="${Arg##[^-]*} "
			}
		fi
	done <<< "$(dtp -h)"

	COMPREPLY=($(compgen -W "$Args" -- "$2"))
}

complete -F _dtp dtp
