#!/usr/bin/env bash
#cito M:644 O:0 G:0 T:/usr/share/bash-completion/completions/apt-download-deps
#------------------------------------------------------------------------------
# Project Name      - PerlProjects/source/apt-download-deps/completions
# Started On        - Mon 11 Jan 16:14:29 GMT 2021
# Last Change       - Sat 22 Jan 00:11:03 GMT 2022
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# This is the bash completion script for `apt-download-deps`.
#------------------------------------------------------------------------------

_aptdownloaddeps() {
	local Option Arg Args Packages

	while read; do
		if [[ $REPLY =~ ^[[:space:]]{2} ]]; then
			Option=${REPLY%% - *}
			for Arg in ${Option//,/}; {
				Args+="${Arg##[^-]*} "
			}
		fi
	done <<< "$(apt-download-deps -h)"

	if [[ $2 == -* ]]; then
		COMPREPLY=(`compgen -W "$Args" -- "$2"`)
	else
		Packages=`_xfunc dpkg _comp_dpkg_installed_packages`
		COMPREPLY=(`compgen -W "$Packages" -- "$2"`)
	fi
}

complete -F _aptdownloaddeps apt-download-deps
