#!/usr/bin/env bash
#cito M:644 O:0 G:0 T:/usr/share/bash-completion/completions/gub
#------------------------------------------------------------------------------
# Project Name      - PerlProjects/source/gub/completions
# Started On        - Mon 16 Mar 16:56:52 GMT 2020
# Last Change       - Mon 16 Mar 16:56:59 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# This is the bash completion script for `gub`.
#------------------------------------------------------------------------------

_gub(){
	while read; do
		if [[ $REPLY =~ ^[[:space:]]{2} ]]; then
			Option=${REPLY%% - *}
			for Arg in ${Option//,/}; {
				Args+="${Arg##[^-]*} "
			}
		fi
	done <<< "$(gub -h)"

	COMPREPLY=(`compgen -W "$Args" -- "$2"`)

	unset Option Arg Args
}

complete -F _gub gub
