#!/usr/bin/env bash
#cito M:644 O:0 G:0 T:/usr/share/bash-completion/completions/ubuchk
#------------------------------------------------------------------------------
# Project Name      - PerlProjects/source/ubuchk/completions
# Started On        - Mon 29 Jan 18:47:58 GMT 2018
# Last Change       - Tue  3 Mar 00:24:32 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# This is the bash completion script for `ubuchk` & `ubuchk-db`.
#------------------------------------------------------------------------------

_ubuchk(){
	case $1 in
		ubuchk)
			while read; do
				if [[ $REPLY =~ ^[[:space:]]{2} ]]; then
					Option=${REPLY%% - *}

					case $Option in
						*=*) Option="${REPLY%%=*}=" ;;
					esac

					for Arg in ${Option//,/}; {
						Args+="${Arg##[^-]*} "
					}
				fi
			done <<< "$($1 -h)"

			case $3 in
					--query|-Q)
						printf -v Args '%s ' `ubuchk --list-dbalerts`
						COMPREPLY=(`compgen -W "$Args" -- "$2"`) ;;
					--key|-k)
						compopt -o nospace

						printf -v Args '%s ' `ubuchk --list-keys`
						COMPREPLY=(`compgen -S '=' -W "$Args" -- "$2"`) ;;
					*)
						COMPREPLY=(`compgen -W "$Args" -- "$2"`) ;;
			esac

			unset Option Arg Args ;;
		ubuchk-db)
			COMPREPLY=(`compgen -W '-h --help -v --version' -- "$2"`) ;;
	esac
}

complete -F _ubuchk ubuchk{,-db}
