#!/usr/bin/env bash
#cito M:644 O:0 G:0 T:/usr/share/bash-completion/completions/ubuchk
#------------------------------------------------------------------------------
# Project Name      - PerlProjects/source/ubuchk/completions
# Started On        - Mon 29 Jan 18:47:58 GMT 2018
# Last Change       - Thu 20 Feb 04:46:54 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# This is the bash completion script for `ubuchk`.
#------------------------------------------------------------------------------

_ubuchk(){
	while read; do
		if [[ $REPLY =~ ^[[:space:]]{2} ]]; then
			Option=${REPLY%% - *}
			for Arg in ${Option//,/}; {
				Args+="${Arg##[^-]*} "
			}
		fi
	done <<< "$(ubuchk -h)"

	COMPREPLY=(`compgen -W "$Args" -- "$2"`)

	unset Option Arg Args
}

complete -F _ubuchk ubuchk
