#!/bin/sh

#------------------------------------------------------------------------------
# Project Name      - PerlProjects/source/ubuchk/postinst
# Started On        - Mon  2 Mar 16:05:09 GMT 2020
# Last Change       - Fri  1 Jan 19:15:05 GMT 2021
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# Creates a symbolic link for Bash completion support. This is mainly, but not
# solely, for use with UbuChk Debian packages.
#------------------------------------------------------------------------------

CompFile='/usr/share/bash-completion/completions/ubuchk'

if [ -f "$CompFile" -a "${CompFile%/*}" ]; then
	if ! [ -w "${CompFile%/*}" ]; then
		printf "ERROR: Root access required.\n" 1>&2
	else
		if ! [ -L "${CompFile}-db" ]; then
			if ! ln -s "$CompFile" "${CompFile}-db"; then
				printf 'ERROR: Failed to create symbolic link.\n' 1>&2
			else
				printf "Symbolic link for '${CompFile##*/}-db' created.\n"
			fi
		else
			printf "Symbolic link for '${CompFile##*/}-db' already exists.\n"
		fi
	fi
else
	printf 'ERROR: Bash completion file '${CompFile##*/}' not found.\n' 1>&2
fi
