#!/bin/sh

#------------------------------------------------------------------------------
# Project Name      - PerlProjects/source/ubuchk/postinst
# Started On        - Mon  2 Mar 16:05:09 GMT 2020
# Last Change       - Sun  8 Mar 17:07:54 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# This short script simply creates a symbolic link for Bash completion
# support, and is mainly, but not solely, for use with UbuChk Debian packages.
#------------------------------------------------------------------------------

CompFile='/usr/share/bash-completion/completions/ubuchk'

if [ -f "$CompFile" ]; then
	if ! [ -w "${CompFile%/*}" ]; then
		printf "ERROR: Root access required.\n" 1>&2
		exit 0
	else
		if ! [ -L "${CompFile}-db" ]; then
			if ! command -v ln 1> /dev/null 2>&1; then
				printf "ERROR: Command 'ln' not found.\n" 1>&2
				exit 0
			fi

			if ! ln -s "$CompFile" "${CompFile}-db"; then
				printf 'ERROR: Failed to create symbolic link.\n' 1>&2
				exit 0
			else
				printf "Symbolic link for '${CompFile##*/}-db' created.\n"
			fi
		else
			printf "Symbolic link for '${CompFile##*/}-db' already exists.\n"
		fi
	fi
else
	printf 'ERROR: Bash completion file '${CompFile##*/}' not found.\n' 1>&2
	exit 0
fi
