#!/bin/sh

#------------------------------------------------------------------------------
# Project Name      - PerlProjects/source/ubuchk/postrm
# Started On        - Mon  2 Mar 16:05:09 GMT 2020
# Last Change       - Tue  3 Mar 01:56:10 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# This short script simply removes the previously created symbolic link for
# Bash completion support, and is mainly, but not solely, for use with UbuChk
# Debian packages.
#------------------------------------------------------------------------------

CompFile='/usr/share/bash-completion/completions/ubuchk-db'

if [ -L "$CompFile" ]; then
	if ! [ -w "${CompFile%/*}" ]; then
		printf "ERROR: Root access required.\n" 1>&2
		exit 1
	else
		if [ -L "$CompFile" ]; then
			if ! command -v rm 1> /dev/null 2>&1; then
				printf "ERROR: Command 'rm' not found.\n" 1>&2
				exit 1
			fi

			if ! rm "$CompFile"; then
				printf 'ERROR: Failed to remove old symbolic link.\n' 1>&2
				exit 1
			else
				printf "Symbolic link for '${CompFile##*/}' removed.\n"
			fi
		else
			printf "Symbolic link for '${CompFile##*/}' not found.\n"
			exit 0
		fi
	fi
else
	printf "Symbolic link '${CompFile##*/}' not found.\n"
fi
