#!/bin/sh
#cito M:755 O:0 G:0 T:/usr/local/bin/ubuchk-db
#------------------------------------------------------------------------------
# Project Name      - PerlProjects/source/ubuchk/ubuchk-db
# Started On        - Mon  2 Mar 15:21:20 GMT 2020
# Last Change       - Wed 11 Nov 03:56:08 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# Bourne shell script responsible for updating the UbuChk database. I chose to
# use shell rather than Perl because I'm feeling lazy; besides, it'll suffice.
#
# If Cito is found, it'll use that instead, with the `--clobber` flag.
#
# Dependencies:
#
#   coreutils (>= 8.25-2)
#   wget (>= 1.17.1-1) | curl (>= 7.47.0-1) | cito (>= 2020-02-29)
#------------------------------------------------------------------------------

CurVer='2020-11-11'
Progrm=${0##*/}

Err(){
	printf 'ERROR: %s\n' "$2" 1>&2
	[ $1 -eq 1 ] && exit 1
}

while [ "$1" ]; do
	case $1 in
		--help|-h)
			printf 'Usage: %s [-h, --help | -v, --version]\n' "$Progrm"
			exit 0 ;;
		--version|-v)
			printf '%s\n' "$CurVer"; exit 0 ;;
		*)
			Err 1 'Incorrect option(s) specified.' ;;
	esac
	shift
done

[ `id -u` -eq 0 ] || Err 1 'Root access is required.'

GHUser='terminalforlife'

YNInput(){
	printf '%s [Y/N] ' "$1"
	read Answer

	case $Answer in
		[Yy]|[Yy][Ee][Ss])
			return 0 ;;
		[Nn]|[Nn][Oo])
			return 1 ;;
		*)
			printf 'ERROR: Invalid response -- quitting.\n'
			exit 1 ;;
	esac
}

if YNInput "Update UbuChk's alert database?"; then
	if ! command -v cito 1> /dev/null 2>&1; then
		DBPath="/usr/share/${Progrm%-*}/database"
		URL="https://raw.githubusercontent.com/$GHUser"

		if command -v wget 1> /dev/null 2>&1; then
			DLoader="wget -qO $DBPath"
		elif command -v curl 1> /dev/null 2>&1; then
			DLoader="curl -so $DBPath"
		else
			Err 1 "Neither 'curl' nor 'wget' were found."
		fi

		FullURL="$URL/PerlProjects/master/source/ubuchk/database"
		if $DLoader "$FullURL"; then
			printf 'Database successfully updated.\n'
		else
			Err 1 "File '${FullURL##*/}' failed to download via ${DLoader%% *}(1)."
		fi
	else
		printf "Cito found; handing '$Progrm' to it instead.\n"
		cito -r "$GHUser" PerlProjects master source/ubuchk/database
	fi
else
	printf 'Database update declined -- skipping.\n'
fi

if YNInput "Update UbuChk's rootkit database?"; then
	if ! command -v cito 1> /dev/null 2>&1; then
		DBPath="/usr/share/${Progrm%-*}/database-rk"
		URL="https://raw.githubusercontent.com/$GHUser"

		if command -v wget 1> /dev/null 2>&1; then
			DLoader="wget -qO $DBPath"
		elif command -v curl 1> /dev/null 2>&1; then
			DLoader="curl -so $DBPath"
		else
			Err 1 "Neither 'curl' nor 'wget' were found."
		fi

		FullURL="$URL/PerlProjects/master/source/ubuchk/database-rk"
		if $DLoader "$FullURL"; then
			printf 'Database successfully updated.\n'
		else
			Err 1 "File '${FullURL##*/}' failed to download via ${DLoader%% *}(1)."
		fi
	else
		printf "Cito found; handing '$Progrm' to it instead.\n"
		cito -r "$GHUser" PerlProjects master source/ubuchk/database-rk
	fi
else
	printf 'Database update declined -- skipping.\n'
fi
