#!/usr/bin/env bash
#cito M:644 O:0 G:0 T:/usr/share/bash-completion/completions/tudu
#------------------------------------------------------------------------------
# Project Name      - PerlProjects/source/tudu/completions
# Started On        - Mon 29 Jan 18:47:58 GMT 2018
# Last Change       - Sat 22 Jan 00:11:47 GMT 2022
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# This is the bash completion script for tudu.
#------------------------------------------------------------------------------

_tudu() {
	local Option Args Arg

	while read; do
		if [[ $REPLY =~ ^[[:space:]]{2} ]]; then
			Option=${REPLY%% - *}
			for Arg in ${Option//,/}; {
				Args+="${Arg##[^-]*} "
			}
		fi
	done <<< "$(tudu -h)"

	COMPREPLY=($(compgen -W "$Args" -- "$2"))
}

complete -F _tudu -o default tudu
