.TH "TUDU" "1" "2020-11-26" "TuDu 2020-11-26" "TuDu"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ad l
.nh
.SH "NAME"
tudu \- N/A
.SH "SYNOPSIS"
tudu [OPTS]
.SH "DESCRIPTION"
N/A
.SH "OPTIONS"
\fB-h\fR, \fB--help\fR, \fB-?\fR
.RS 4
Display some helpful information.
.RE
.PP
\fB-v\fR, \fB--version\fR
.RS 4
Output the version datestamp.
.SH "NOTES"
N/A
.SH "BUGS"
For bug reports and other issues with \fBTuDu\fR, including suggestions, please report to the below \fBGitHub\fR link, through which the project is developed.
.PP
.RS 2
\fBhttps://github.com/terminalforlife/PerlProjects\fR
.RE
.PP
You may also E-Mail the author of this project, but it's rarely checked.
.RE
.PP
As a last resort, however, one might simply leave a comment over at the below YouTube channel, \fBLearn Linux\fR.
.PP
.RS 2
\fBhttps://www.youtube.com/c/LearnLinux\fR
