#!/usr/bin/env perl
#cito M:600 O:1000 G:1000 T:$HOME/.i3a/battery_monitor
#------------------------------------------------------------------------------
# Project Name      - PerlProjects/source/battery_monitor
# Started On        - Mon 27 Jan 02:54:42 GMT 2020
# Last Change       - Wed 28 Oct 03:52:16 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# Battery monitoring pseudo-daemon. Acts accordingly if the battery is low.
#
# To make effective use of this script, run it like you would most daemons.
# Have it executed in the background when the user logs in.
#
# This script takes no arguments.
#
# Dependencies:
#
#   libgtk2-notify-perl (>= 0.05-5)
#   libtfl-perl (>= 2020-01-03)
#   perl (>= 5.26.1-6)
#   systemd (>= 237-3)
#   upower (>= 0.99.7-2)
#------------------------------------------------------------------------------

use strict;
use warnings;
use autodie;
use TFL 'DepChk';
use Gtk2::Notify '-init', 'battery_monitor';

no warnings 'uninitialized';

my $CurVer = "2020-10-28";

my $LidFile = '/proc/acpi/button/lid/LID0/state';
my $ChassisFile = '/sys/devices/virtual/dmi/id/chassis_type';

sub Notify{
	my $Noti = Gtk2::Notify->new($_[0]);
	$Noti->set_urgency('critical');
	$Noti->show()
}

while (){
	DepChk('upower', 'systemctl');

	# Quit if not a laptop or lid is closed.
	if (open(my $FH, '<', $ChassisFile)){
		chomp(my $Chassis = <$FH>);
		close($FH);

		exit(0) unless $Chassis == 9
	}elsif (open($FH, '<', $LidFile)){
		chomp(my $Lid = <$FH>);
		close($FH);

		exit(0) if split(' ', $Lid) eq 'open'
	}

	my $CurStep;
	foreach (`upower --dump`){
		chomp(my @Arr = split(' ', $_));
		next unless $Arr[0] eq 'percentage:';

		my $PRemains = substr($Arr[1], 0, length($Arr[1]) - 1);

		if ($PRemains < 2){
			Notify("Initiating emergency shutdown in 7s.");
			sleep(7) and system('systemctl poweroff')
		}

		Notify("Battery critical -- shutdown now!") if $PRemains < 3;
		Notify("Battery very low.") if $PRemains < 5;
		Notify("Battery low.") if $PRemains < 10;

		last
	}

	sleep(30)
}
