#!/usr/bin/env perl
#cito M:755 O:0 G:0 T:/usr/bin/cpufreq
#------------------------------------------------------------------------------
# Project Name      - PerlProjects/source/cpufreq
# Started On        - Sat  4 May 15:51:08 BST 2019
# Last Change       - Sun  1 Nov 18:55:47 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# Features:
#
# N/A
#
# Bugs:
#
# N/A
#
# Dependencies:
#
#   perl (>= 5.22.1-9)
#----------------------------------------------------------------------------------

use strict;
use warnings;
use autodie;

no warnings 'uninitialized';

my $CurVer = '2020-11-01';
my $Progrm = 'cpufreq';

sub Usage {
	print(qq{Usage: $Progrm [OPTS]

		  -h, --help               - Display this help information.
		  -v, --version            - Output the version datestamp.
	} =~ tr/\t//dr)
}

foreach (@ARGV) {
	if (/^(--help|-h|-\?)$/) {
		Usage(); exit(0)
	} elsif (/^(--version|-v)$/) {
		print("$CurVer\n"); exit(0)
	} else {
		die('Incorrect option(s) specified')
	}

	shift()
}

my $ProcFile = '/proc/cpuinfo';

-f $ProcFile or die("File '$ProcFile' not found");
-r $ProcFile or die("Read access for '$ProcFile' is denied");

open(my $FH, '<', $ProcFile);

my $CoreCount = 0;
while (<$FH>) {
	chomp(my @Line = split(':'));
	$Line[0] =~ '^cpu MHz' or next;

	$CoreCount++;
	printf("CORE_%d: %.3f\n", $CoreCount, $Line[1] =~ tr/ //dr)
}

close($FH)
