#!/usr/bin/env perl
#cito M:755 O:0 G:0 T:/usr/bin/cpufreq
#------------------------------------------------------------------------------
# Project Name      - PerlProjects/source/cpufreq
# Started On        - Sat  4 May 15:51:08 BST 2019
# Last Change       - Thu 27 Feb 22:23:29 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# Features:
#
# N/A
#
# Bugs:
#
# N/A
#
# Dependencies:
#
#   libtfl-perl (>= 2020-01-03)
#   perl (>= 5.22.1-9)
#----------------------------------------------------------------------------------

use strict;
use warnings;
use autodie;
use TFL 'Err';

no warnings 'uninitialized';

my $CurVer = '2020-02-27';

sub Usage{
	print(qq{Usage: $TFL::PROGNAME [OPTS]

		  -h, --help               - Display this help information.
		  -v, --version            - Output the version datestamp.
	} =~ tr/\t//dr)
}

foreach (@ARGV){
	if (/^(--help|-h|-\?)$/){
		Usage(); exit(0)
	}elsif (/^(--version|-v)$/){
		print("$CurVer\n"); exit(0)
	}else{
		Err(1, "Incorrect option(s) specified")
	}

	shift()
}

my $ProcFile = '/proc/cpuinfo';

Err(1, "File '$ProcFile' not found.") unless -f $ProcFile;
Err(1, "Read access for '$ProcFile' is denied.") unless -r $ProcFile;

open(my $FH, '<', $ProcFile);

my $CoreCount = 0;
while (<$FH>){
	chomp(my @Line = split(':'));
	next unless $Line[0] =~ '^cpu MHz';

	$CoreCount++;
	printf("CORE_%d: %.3f\n", $CoreCount, $Line[1] =~ tr/ //dr)
}

close($FH)
