#!/usr/bin/env perl
#cito M:755 O:0 G:0 T:/usr/bin/cpufreq
#------------------------------------------------------------------------------
# Project Name      - PerlProjects/source/cpufreq
# Started On        - Sat  4 May 15:51:08 BST 2019
# Last Change       - Sun 10 Apr 22:49:10 BST 2022
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# Features:
#
# N/A
#
# Bugs:
#
# N/A
#
# Dependencies:
#
#   perl (>= 5.26.1)
#------------------------------------------------------------------------------

use feature 'say';
use strict;
use warnings;

no warnings 'uninitialized';

use constant VERSION => '2022-04-10';
use constant PROGRAM => 'cpufreq';

sub Usage() {
	print(qq{Usage: ${\PROGRAM} [OPTS]

		  -h, --help               - Display this help information.
		  -v, --version            - Output the version datestamp.
	} =~ tr/\t//dr)
}

my $ProcFile = '/proc/cpuinfo';

while (defined($ARGV[0])) {
	if ($ARGV[0] =~ '^(--help|-h)$') {
		Usage(); exit(0)
	} elsif ($ARGV[0] =~ '^(--version|-v)$') {
		say(VERSION); exit(0)
	} else {
		die("Err: Incorrect option(s) specified.\n")
	}

	shift()
}

die("Err: File '$ProcFile' not found.\n") unless -f $ProcFile;
die("Err: Read access for '$ProcFile' is denied.\n") unless -r $ProcFile;

open(my $FH, '<', $ProcFile) or die("$!");

while (<$FH>) {
	chomp(my @Line = split(':'));

	next() unless $Line[0] =~ '^cpu MHz';

	my $GHz = substr($Line[1], 1) / 1000;
	printf("CORE_%d: %.2f GHz\n", our $CoreCount++, $GHz)
}

close($FH) or die("$!")
