#!/usr/bin/env perl
#cito M:755 O:0 G:0 T:/usr/bin/fix-ff-gtk
#------------------------------------------------------------------------------
# Project Name      - PerlProjects/source/fix-ff-gtk (Fix Firefox GTK)
# Started On        - Fri 10 Jan 19:32:40 GMT 2020
# Last Change       - Fri 20 Nov 20:59:44 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# A Perl rewrite of the old shell version.
#
# Dependencies:
#
#   libtfl-perl (>= 2020-01-11)
#------------------------------------------------------------------------------

use strict;
use warnings;
use autodie;

my $CurVer = "2020-11-20";
my $Progrm = 'fix-ff-gtk';

my $File = '/usr/bin/firefox';
my $Theme = 'Adwaita';

sub Usage {
	print(qq{Usage: $Progrm [OPTS]

		  -h, --help               - Display this help information.
		  -v, --version            - Output the version datestamp.
		  -N, --non-interactive    - Execute non-interactively.
		  -t, --theme [NAME]       - Where NAME is the chosen theme.

		  The GTK theme $Theme, usually available by default, is needed, unless
		  another is specified.

		  This script will work globally, meaning ALL users, regardless of
		  their chosen theme, will use the $Theme GTK theme for their use of
		  Firefox.

		  It's possible that changes to the below file would not be desired, in
		  which case it would have to be restored from a backup, or Firefox
		  would need to be reinstalled.

		  Using the non-interactive feature assumes yes.
	} =~ tr/\t//dr)
}

my $NonInt = 'false';

while (defined($ARGV[0])){
	if ($ARGV[0] =~ '^(--help|-h|-\?)$'){
		Usage(); exit(0)
	}elsif ($ARGV[0] =~ '^(--version|-v)$'){
		print("$CurVer\n"); exit(0)
	}elsif ($ARGV[0] =~ '^(--non-interactive|-N)$'){
		$NonInt = 'true'
	}else{
		die("Incorrect option(s) specified.")
	}

	shift()
}

sub YNInput{
	print("$_[0] [Y/N] ");
	my $Reply = <STDIN>;

	if ($Reply =~ '^([Nn]|[Nn][Oo])$'){
		return(0)
	}elsif (length($Reply) == 0 or $Reply !~ '^([Yy]|[Yy][Ee][Ss])$'){
		return(2)
	}else{
		return(1)
	}
}

exit(1) unless YNInput("Make permanent changes to '$File'?");

Err(1, 'Root access is required.') unless $< == 0;
die("File '$File' not found.") unless -f $File;

open(my $FH, '+<', $File);

my @Data = <$FH>;

truncate($FH, 0);
seek($FH, 0, 0);

foreach (@Data){
	if (/^[[:space:]]+exec \$MOZ_LIBDIR\/\$MOZ_APP_NAME "\$@"$/){
		print($FH $_ =~ s/^([[:space:]]+)(.*)$/$1 GTK_Theme='$Theme' $2/r)
	}else{
		print($FH $_)
	}
}

close($FH);
