#!/usr/bin/env perl
#cito M:755 O:0 G:0 T:/usr/bin/notify-upgrade
#------------------------------------------------------------------------------
# Project Name      - PerlProjects/source/notify-upgrade
# Started On        - Wed 15 Jan 00:45:46 GMT 2020
# Last Change       - Mon 18 Jan 22:58:52 GMT 2021
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# Requires that `apt-get` be found in `/usr/bin/`, else fail. This is to be
# expected in most, if not all Debian/Ubuntu-based distributions of Linux.
#
# Dependencies:
#
#  apt (>= 1.2.32)
#  libgtk2-notify-perl (>= 0.05-4build2)
#  perl (>= 5.22.1-9)
#------------------------------------------------------------------------------

use strict;
use warnings;
use autodie;

no warnings 'uninitialized';

my $CurVer = '2021-01-18';
my $Progrm = 'notify-upgrade';

sub Usage {
	print(qq{Usage: $Progrm [OPTS]

		  -h, --help               - Display this help information.
		  -v, --version            - Output the version datestamp.

		  Per the provided cron job, the check occurs every hour.
	} =~ tr/\t//dr)
}

while (defined($ARGV[0])) {
	if ($ARGV[0] =~ '^(--help|-h|-\?)$') {
		Usage(1); exit(0)
	} elsif ($ARGV[0] =~ '^(--version|-v)$') {
		print("$CurVer\n"); exit(0)
	} else {
		die("Incorrect option(s) specified")
	}

	shift(@ARGV)
}

-x '/usr/bin/apt-get' or die("File '/usr/bin/apt-get' missing");

my (%Stats, $Total);

# Works with Ubuntu 18.04. The output from apt-get(8) changed slightly since
# 16.04 so this probably won't work in anything older than 18.04.
foreach (`apt-get -s dist-upgrade`) {
	next unless /^[0-9]+ to upgrade,/;

	my @Arr = split(' ', $_);

	%Stats = (
		'Category' => {
			'Upgrade' => $Arr[0],
			'Install' => $Arr[3],
			'Remove' => $Arr[7],
			'Skip' => $Arr[11]
		},

		'Total' => $Total
	);

	last
}

my $Category = $Stats{'Category'};
$Total += $_ foreach values(%$Category);

if ($Total > 0) {
	use Gtk2::Notify '-init', 'Notify-Upgrade';

	my $Message = "Detected $Total available package change(s).";
	my $Noti = Gtk2::Notify->new("Notify Upgrade $Message");
	$Noti->set_urgency('normal');
	$Noti->show()
}
