#!/usr/bin/env perl

#----------------------------------------------------------------------------------
# Project Name      - PerlProjects/source/notify-upgrade
# Started On        - Wed 15 Jan 00:45:46 GMT 2020
# Last Change       - Sun  1 Nov 18:05:43 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# Requires that `apt-get` be found in `/usr/bin/`, else fail. This is to be
# expected in most, if not all Debian/Ubuntu-based distributions of Linux.
#
# Dependencies:
#
#  apt (>= 1.2.32)
#  libgtk2-notify-perl (>= 0.05-4build2)
#----------------------------------------------------------------------------------

use strict;
use warnings;
use autodie;

no warnings 'uninitialized';

my $Progrm = 'notify-upgrade';
my $CurVer = "2020-11-01";

sub Usage {
	print(qq{Usage: $Progrm [OPTS]

		  -h, --help               - Display this help information.
		  -v, --version            - Output the version datestamp.

		  Per the provided cron job, the check occurs every hour.
	} =~ tr/\t//dr)
}

while (defined($ARGV[0])) {
	if ($ARGV[0] =~ '^(--help|-h|-\?)$') {
		Usage(1); exit(0)
	} elsif ($ARGV[0] =~ '^(--version|-v)$') {
		print("$CurVer\n"); exit(0)
	} else {
		die("Incorrect option(s) specified")
	}

	shift(@ARGV)
}

-x '/usr/bin/apt-get' or die("File '/usr/bin/apt-get' missing");

my (%Stats, $Total);

foreach (`apt-get -s dist-upgrade`) {
	next unless /^[0-9]+ upgraded,/;

	my @Arr = split(' ', $_);

	%Stats = (
		'Category' => {
			'Upgrade' => $Arr[0],
			'Install' => $Arr[2],
			'Remove' => $Arr[5],
			'Skip' => $Arr[9]
		},

		'Total' => $Total
	);

	last
}

my $Category = $Stats{'Category'};
$Total += $_ foreach values(%$Category);

if ($Total > 0) {
	use Gtk2::Notify '-init', 'Notify-Upgrade';

	my $Message = "Detected $Total available package change(s).";
	my $Noti = Gtk2::Notify->new("Notify Upgrade $Message");
	$Noti->set_urgency('critical');
	$Noti->show()
}
