#!/usr/bin/env perl

#------------------------------------------------------------------------------
# Project Name      - PerlProjects/source/ubuchk-index
# Started On        - Tue  4 Feb 23:30:37 GMT 2020
# Last Change       - Wed  5 Feb 00:58:30 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# This will handle displaying descriptions for various alert IDs to the user.
#------------------------------------------------------------------------------
# Dependencies:
#
#   libtext-wrapi18n-perl (>= 0.06-7.1)
#   libtfl-perl (>= 2020-01-03)
#   perl (>= 5.22.1-9)
#------------------------------------------------------------------------------

use strict;
use warnings;
use autodie;
use TFL 'Err';
use Text::Wrap;

no warnings 'uninitialized';

my $CurVer = '2020-02-05';

#my $Database = '/usr/share/ubuchk/ubuchk-db';
my $Database = 'ubuchk-db';

sub Usage{
	print(qq{            @{[uc($TFL::PROGNAME)]} ($CurVer)
		            $TFL::AUTHOR

		            ...

		SYNTAX:     $TFL::PROGNAME [OPTS]

		OPTS:       --help|-h|-?            - Display this help information.
		            --version|-v            - Output the version datestamp.

		FILE:       $Database
	} =~ tr/\t//dr)
}

while (defined($ARGV[0])){
	if ($ARGV[0] =~ '^(--help|-h|-\?)$'){
		Usage(1); exit(0)
	}elsif ($ARGV[0] =~ '^(--version|-v)$'){
		print("$CurVer\n"); exit(0)
	}elsif ($ARGV[0] =~ '^-'){
		Err(1, "Incorrect option(s) specified.")
	}else{
		last
	}

	shift()
}

Err(1, "Invalid alert ID.") unless $ARGV[0] =~ '^[0-9]{4}$';

open(my $FH, '<', $Database);

my ($Found, @Body);
while (<$FH>){
	chomp();

	if (/^:[0-9,]+$/){
		last if $Found eq 'true';

		my @CurIDs = split(',', substr($_, 1));
		foreach (@CurIDs){
			next unless $_ == $ARGV[0];

			$Found = 'true';
			last
		}
	}elsif ($Found eq 'true'){
		@Body = $_;
	}
}

close($FH);

Err(1, "Alert '$ARGV[0]' not found.") unless $Found eq 'true';

print("$_\n") foreach @Body
