#!/usr/bin/env perl

#------------------------------------------------------------------------------
# Project Name      - PerlProjects/source/usersums
# Started On        - Mon 25 Jan 21:02:07 GMT 2021
# Last Change       - Mon 25 Jan 22:29:47 GMT 2021
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# Save a recursive list of all files and their MD5 hashes in HOME. The MD5 file
# format is the same as the standard md5sum(1) uses. The file is saved to HOME
# as '.md5sums', unless otherwise specified.
#
# This will take a LONG time depending on the data to be processed.
#
# NOTE: Symlinks are not followed.
#------------------------------------------------------------------------------

require Digest::MD5;
require File::Find;

use v5.26;
use strict;
use warnings;
use autodie;
use File::Find 'find';
use Digest::MD5 'md5_hex';

no warnings 'uninitialized', 'File::Find';

my $Target = $ENV{'HOME'};
my $Output = "$Target/.md5sums";

my @Files;
sub DoFind {
	my $Path = $File::Find::name;
	return() if $Path eq $Output;
	-f $Path and push(@Files, $Path)
}

my %FindOpts = (
	'wanted' => \&DoFind,
	'no_chdir' => 1,
	'follow' => 0
);

find(\%FindOpts, $Target);

open(my $SaveHandle, '>', $Output) or die();

while (1) {
	print("Overwrite existing '$Output' file? [Y/N] ");

	chomp(my $Input = <STDIN>);

	if ($Input =~ '^([Yy]|[Yy][Ee][Ss])$') {
		my $MD5 = Digest::MD5->new();

		my $Hash;
		foreach (@Files) {
			if (open(my $HashHandle, '<', $_)) {
				$MD5->addfile($HashHandle);
				$Hash = $MD5->hexdigest();
				close($HashHandle)
			} else {
				warn("Cannot open '$_' for reading")
			}

			printf($SaveHandle "%s  %s\n", $Hash, $_);
		}

		close($SaveHandle);
		last()
	} elsif ($Input =~ '^([Nn]|[Nn][Oo])$') {
		print("Nothing to do -- quitting.\n");
		last()
	} else {
		print(STDERR "ERROR: Invalid response.\n")
	}
}
